version: '3'
services:
  nodejs:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: notifyer_backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`notifyer.capicua.org.es`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=6923"
    networks:
      - traefik-global-proxy 
      
networks:
  traefik-global-proxy:
    external: true